name: Deploy to ConoHa WING
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: npm install
        
      - name: Build Astro site
        run: npm run build
        
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          # GitHubのシークレットから鍵を取得し、正しい形式でファイルに保存する
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          
          # デバッグ: SSHとrsyncで接続テスト (詳細出力モード)
          ssh -v -p ${{ secrets.REMOTE_PORT }} -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "ls -la"
          
      - name: Deploy with rsync
        run: |
          # デバッグオプション(-v)を追加して詳細な出力を得る
          rsync -avzr --delete -e "ssh -v -p ${{ secrets.REMOTE_PORT }} -i ~/.ssh/id_rsa" ./dist/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}